language: cpp
compiler:
- gcc
- clang

os:
- linux
- osx

before_install:
- sudo pip install cpp-coveralls --use-mirrors

script: 
- mkdir build; pushd build
- cmake .. -DVERBOSE=1
- make -j2 tests

after_success:
  - coveralls --exclude tests

