
clone_depth: 5

os: Visual Studio 2015

init:
- ps: cinst cmake 2>&1 | Out-Null
- ps: cmake --version

install:
# Use HTTPs for github  
- ps: cat .gitmodules | %{$_ -replace "git@github\\.com:","https://github.com/"} > .gitmodules
- ps: git submodule update --init --recursive

build_script:
- ps: cd build

- ps: cmake .. -DVERBOSE=1 -DUSE_CCACHE=0 
- ps: nmake

test_script:

- ps: nmake test