
clone_depth: 5

init:
- ps: cinst cmake 2>&1 | Out-Null
- ps: cmake --version

install:
- ps: git submodule update --init --recursive


build_script:
- ps: cd build

- ps: cmake .. -DVERBOSE=1 -DUSE_CCACHE=0 
- ps: nmake

test_script:

- ps: nmake test