
clone_depth: 5

init:
- ps: cinst cmake 2>&1 | Out-Null

install:

- ps: git submodule update --init --recursive
- ps: $env:Path="C:\Ruby21\bin;C:/tools/ruby22/bin;$($env:Path);C:\tools\php;C:\ProgramData\chocolatey\lib\ant"

- ps: cmake --version

build_script:

- ps: cd build

- ps: cmake .. -DVERBOSE=1 -DUSE_CCACHE=0 
- ps: nmake

test_script:

- ps: nmake test